# Generated by Django 3.2 on 2023-01-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('health', models.IntegerField()),
                ('mana', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('region', models.CharField(max_length=200, unique=True)),
                ('established_since', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
            ],
            options={
                'ordering': ['-established_since'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('position', models.CharField(max_length=200)),
                ('play_since', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mains', to='eSportManager.champion')),
                ('current_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='eSportManager.team')),
            ],
            options={
                'ordering': ['-play_since'],
            },
        ),
    ]
