# Generated by Django 3.2 on 2023-01-18 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eSportManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='champ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mains', to='eSportManager.champion'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='players', to='eSportManager.team'),
        ),
    ]
