# Generated by Django 3.2 on 2023-01-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eSportManager', '0002_auto_20230118_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.RemoveField(
            model_name='player',
            name='play_since',
        ),
    ]
