# Generated by Django 3.2 on 2023-01-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSportManager', '0010_remove_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.IntegerField(choices=[(0, 'Top'), (1, 'Jungle'), (2, 'Mid'), (3, 'ADC'), (4, 'Support')], default=0),
        ),
    ]
