# Generated by Django 3.2 on 2023-01-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eSportManager', '0011_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='current_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coach', to='eSportManager.team'),
        ),
    ]
